#!/bin/bash
#SBATCH --job-name=hiC_mapping_crossed_refAZN
#SBATCH --output=hiC_mapping_crossed_refAZN_%j_output
#SBATCH --error=hiC_mapping_crossed_refAZN_%j_error
#SBATCH --export=ALL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --cpus-per-task=32
#SBATCH --partition=standard
#SBATCH --time=23:30:00

#load directories
INDIR_hic=/home/igomez/genome_assembly_helodes_thesis/raw_data/hiC
OUTDIR=/home/igomez/genome_assembly_helodes_thesis/hiC_mapping_crossed
SOFTWAREDIR=/home/igomez/software
REF=~/genome_assembly_helodes_thesis/C0_clean_assemblies/1JMC18.fasta

##actívate conda
source ~/anaconda3/etc/profile.d/conda.sh
conda activate ref_map
    ### Map HiC reads to ref using bwa mem

## First we need to map them as single reads, but we do it twice for both DNA strands

mkdir -p $OUTDIR/refAZN/rawbamdir

bwa mem -t 16 $REF $INDIR_hic/4JMC19C_R1_trimmed.fastq.gz |
samtools view -@ 16 -Sb - > $OUTDIR/refAZN/rawbamdir/refAZN_1.bam

bwa mem -t 16 $REF $INDIR_hic/4JMC19C_R2_trimmed.fastq.gz |
samtools view -@ 16 -Sb - > $OUTDIR/refAZN/rawbamdir/refAZN_2.bam

echo "single read mapping done for refAZN"

## We will eliminate the 3' end as it is redundant with the 5' end of the other strand.

mkdir -p $OUTDIR/refAZN/filtbamdir

samtools view -h $OUTDIR/refAZN/rawbamdir/refAZN_1.bam | perl $SOFTWAREDIR/filter_five_end.pl | \
samtools view -Sb - > $OUTDIR/refAZN/filtbamdir/refAZN_1.bam
samtools view -h $OUTDIR/refAZN/rawbamdir/refAZN_2.bam | perl $SOFTWAREDIR/filter_five_end.pl | \
samtools view -Sb - > $OUTDIR/refAZN/filtbamdir/refAZN_2.bam

echo " 3' end eliminated from refAZN "

## Now we will pair the two mapped DNA strands using  Map quality 0! is an important parameter which
##outputs a sorted, mapping quality filtered, paired-end BAM file. We then add read groups to this BAM
##file using Picard Tools.

    mkdir -p $OUTDIR/refAZN/tmpdir

    perl $SOFTWAREDIR/two_read_bam_combiner.pl $OUTDIR/refAZN/filtbamdir/refAZN_1.bam \
    $OUTDIR/refAZN/filtbamdir/refAZN_2.bam samtools 1 | \
    samtools view -bS -t ${REF}.fai - | samtools sort -@ 16 -o $OUTDIR/refAZN/tmpdir/refAZN.bam -

    mkdir -p $OUTDIR/refAZN/pairdir
    picard -Xmx100g AddOrReplaceReadGroups INPUT=$OUTDIR/refAZN/tmpdir/refAZN.bam OUTPUT=$OUTDIR/refAZN/pairdir/refAZN.bam ID=refAZN LB=refAZN SM=scaffolding PL=ILLUMINA PU=none

echo "read pairing done for refAZN"

## Remove PCR duplicates from pair-end BAM file

    mkdir -p $OUTDIR/refAZN/repdir
    picard -Xmx100g MarkDuplicates INPUT=$OUTDIR/refAZN/pairdir/refAZN.bam OUTPUT=$OUTDIR/refAZN/repdir/refAZN_final.bam METRICS_FILE=$OUTDIR/refAZN/repdir/metrics.replicates.txt TMP_DIR=$OUTDIR/refAZN/tmpdir ASSUME_SORTED=TRUE VALIDATION_STRINGENCY=LENIENT REMOVE_DUPLICATES=TRUE

echo "PCR duplicates removed from refAZN"

##Finally, index the final file and calculate statistics to monitor the mapping

samtools index $OUTDIR/refAZN/repdir/refAZN_final.bam

perl $SOFTWAREDIR/get_stats.pl $OUTDIR/refAZN/repdir/refAZN_final.bam > $OUTDIR/refAZN/repdir/refAZN_final.bam.stats

## Not only calculate statistics of the final file but also from intermediate steps. Add them to flagstat file
    touch $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats raw bam R1" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/rawbamdir/refAZN_1.bam >> $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats raw bam R2" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/rawbamdir/refAZN_2.bam >> $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats bam chimeric reads filtered R1" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/filtbamdir/refAZN_1.bam >> $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats bam chimeric reads filtered R2" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/filtbamdir/refAZN_2.bam >> $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats bam paired and mapping quality filtered" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/tmpdir/refAZN.bam >> $OUTDIR/refAZN/flagstat.txt
    echo ">>> Stats final bam (duplicates filtered)" >> $OUTDIR/refAZN/flagstat.txt
    samtools flagstat $OUTDIR/refAZN/repdir/refAZN_final.bam >> $OUTDIR/refAZN/flagstat.txt

echo "index and stats done for refAZN"


conda deactivate

### SOFTWARE VERSIONS
# fastp 0.23.4
# bwa 0.7.15
# Picard 1.141
# Arima mapping pipeline V03
